name = "runup-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
# You can define non-secret environment variables here if you need them in the future.

[d1_databases]
# This tells Wrangler that your worker is connected to the 'countdown-db' database.
# Make sure the binding name ('DB') matches what you use in your code (env.DB).
binding = "DB"
database_name = "countdown-db"
database_id = "26aed731-2397-4f6a-b0a1-caa9cabb3320" # You need to fill this in.

# This is the most important part!
# It tells Wrangler to enable Node.js compatibility, which allows it to find and bundle 'bad-words'.
[dev]
node_compat = true