name = "runup-api"
main = "src/index.js"
compatibility_date = "2024-01-01"
node_compat = true

[d1_databases]
binding = "DB"
database_name = "countdown-db"
database_id = "26aed731-2397-4f6a-b0a1-caa9cabb3320"